const { createRunOncePlugin, withProjectBuildGradle } = require('@expo/config-plugins');

const marker = '// @generated by withAndroidWorkManagerResolution';

function withAndroidWorkManagerResolution(config) {
  return withProjectBuildGradle(config, (projectConfig) => {
    if (projectConfig.modResults.language !== 'groovy') {
      return projectConfig;
    }

    if (!projectConfig.modResults.contents.includes(marker)) {
      projectConfig.modResults.contents += `

${marker}
// Expo Widgets pins Glance to WorkManager 2.7.1, while the Android widget
// package brings WorkManager 2.8.1. Keep both artifacts on the same release.
allprojects {
  configurations.all {
    resolutionStrategy.force 'androidx.work:work-runtime-ktx:2.8.1'
  }
}
`;
    }

    return projectConfig;
  });
}

module.exports = createRunOncePlugin(
  withAndroidWorkManagerResolution,
  'with-android-workmanager-resolution',
  '1.0.0',
);
